import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import getCharacters from '../services/api'

const Home: NextPage = () => {
  const [characters, setCharacters] = useState<any[]>([])

  useEffect(() => {
    const load = async () => {
      const data = await getCharacters()
      setCharacters(data)
    }

    load()
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello, World</h1>
      { characters.map((item, key) => (
        <h2 key={key}>{item.name}</h2>
      ))}
    </div>
  )
}

export default Home