import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext, useEffect, useState } from 'react'
import CharacterCard from '../components/CharacterCard'
import Filters from '../components/Filters'
import Search from '../components/Search'
import {CharacterContext} from '../context/CharacterContex/index'
import { Character } from '../interfaces'

const Home: NextPage = () => {
  const { characters } = useContext(CharacterContext)

  console.log('renderizou')

  return (
    <div>
      <Head>
        <title>Squanchy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/squanch.png" />
      </Head>
      <Search />
      <Filters />
      { characters ?
        characters.map((item: Character, key: number) => (
          <CharacterCard key={key} item={item}/>
        ))
        :
        <div className='w-full text-center text-red-600'>
          <h2>Nenhum personagem encontrado! 😔</h2>
        </div>
      }
    </div>
  )
}

export default Home